# Assignment 3: numpy

This assignment is about slicing and .

## How to hand in
The assignment is expected to be published on GitHub, but the actual hand-in is on peergrade and should contain only a link to a MyBinder. Remember her to use the link provided when first registering your notebook with mybinder (not the url taken from your browsers adress field). See the notebook 12-Assignments for more information.

## Create jupyter notebook with 4 data illustrations
1. First create a file with your python module. This is where you should put your functions to be used in the notebook.
2. Second create a function to read the csv file containing Copenhagen city population data and return a numpy array (numpy.ndarray). hint: use np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1) as in the slides
3. Third create a function that can extract the number of all the citizens from native english speaking countries and from non english speaking countries. How many are there of each? (hint remember that with python you can return multiple values from a function).
4. Now create another function that can take 2 arguments:
    - 1: the dataset in the form of a 2dimensional data array where y=data rows and x=[year, area, age nationality, amount].
    - 2: the mask in the form: data[:,3] == 5120 to find swedish or data[:,0] == 1999 to filter on year
the return value must be the filtered dataset.
5. Create another function that can take 2 arguments:
    - a dataset with same characteristics as above and
    - a value for the x-axis (either year, area, age or nationality)
    - return value should be the accumulated population for all x-values.
    - hint: if year is chosen for x then y is all accumulated amounts from all areas, ages and nationalities.
6. Create Illustration 1: In your notebook use the above function and create a 2d array of year as x and accumulated amount as y:
create a line graph of the population change over time for all of Copenhagen
7. Create illustration 2: In your notebook use your module to create a dataset where development of all German citizens can be shown over time
8. Create illustration 3: Show a bar plot of all the 18-25 year old in the different areas of copenhagen and in the same plot show (in a different color) all 60-67 year old in the different areas.
9. Create illustration 4: show a pie chart of age groups (0-10, 10-20, 20-30 ...) in Østerbro part of Copenhagen. create another similar piechart for Vesterbro.

### 2 Create a function to read the csv file containing Copenhagen city population data and return a numpy array.

In [1]:
import my_module

print(my_module.get_data())

[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992   99   89 5100    1]
 [1992   99   90 5180    1]
 [1992   99   93 5100    1]]


### 3 Create a function that can extract the number of all the citizens from native english speaking countries and from non english speaking countries.

How many are there of each?

In [2]:
import my_module

asdfg = my_module.no_english_and_non_english()

native_english, non_english = asdfg

print('Native english:', native_english)
print('Non-english:', non_english)

Native english: [3438 3552 3679 4029 4255 4558 4737 4809 4846 4835 4752 4594 4616 4623
 4504 4566 4711 4991 5169 5492 5562 5747 5887 6186]
Non-english: [461128 462577 463574 467271 472496 479100 483232 486273 490853 494313
 495779 496691 497048 497739 496654 499133 505150 513583 523039 534050
 543488 553693 564285 574109]


### 4 Now create another function that can take 2 arguments

- 1: the dataset in the form of a 2dimensional data array where y=data rows and x=[year, area, age nationality, amount].
- 2: the mask in the form: data[:,3] == 5120 to find swedish or data[:,0] == 1999 to filter on year.
- the return value must be the filtered dataset.

In [5]:
import my_module

data = my_module.get_data()
year_mask = (data[:,0] == 2015)
area_mask = (data[:,1] == 1)
age_mask = (data[:,2] == 25)
nationality_mask = (data[:,3] == 5100)

print('filter by year')
print(my_module.filter_data(data, year_mask), '\n----------------------------')
print('filter by area')
print(my_module.filter_data(data, area_mask), '\n----------------------------')
print('filter by age')
print(my_module.filter_data(data, age_mask), '\n----------------------------')
print('filter by nationality')
print(my_module.filter_data(data, nationality_mask))

filter by year
[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [2015   99   82 5100    1]
 [2015   99   86 5289    1]
 [2015   99   90 5289    1]] 
----------------------------
filter by area
[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992    1  100 5100    1]
 [1992    1  101 5100    2]
 [1992    1  103 5100    1]] 
----------------------------
filter by age
[[2015    1   25 5100 1107]
 [2015    1   25 5103    1]
 [2015    1   25 5104    6]
 ...
 [1992   99   25 5244    1]
 [1992   99   25 5436    1]
 [1992   99   25 5438    2]] 
----------------------------
filter by nationality
[[2015    1    0 5100  614]
 [2015    1    1 5100  540]
 [2015    1    2 5100  485]
 ...
 [1992   99   87 5100    2]
 [1992   99   89 5100    1]
 [1992   99   93 5100    1]]


### 5 Create another function that can take 2 arguments:
- a dataset with same characteristics as above and
- a value for the x-axis (either year, area, age or nationality)
- return value should be the accumulated population for all x-values.

In [4]:
import my_module

data = my_module.get_data()

print('year\n', my_module.accumulated_population_of_xval(data, 0, 2015), '\n----------------------------')
print('area\n', my_module.accumulated_population_of_xval(data, 1, 1), '\n----------------------------')
print('age\n', my_module.accumulated_population_of_xval(data, 2, 25), '\n----------------------------')
print('nationality\n', my_module.accumulated_population_of_xval(data, 3, 5100))

year
 [   614    616    617 ... 580293 580294 580295] 
----------------------------
area
 [    614     616     617 ... 1082099 1082101 1082102] 
----------------------------
age
 [  1107   1108   1114 ... 331406 331407 331409] 
----------------------------
nationality
 [     614     1154     1639 ... 10728941 10728942 10728943]
